# ESM-2 Transformer Configuration for CDR Prediction and Antibody Design
# Phytovenomics ML Platform

# Model Configuration
model:
  # ESM-2 model selection
  # Options: esm2_t6_8M_UR50D (smallest), esm2_t12_35M_UR50D, esm2_t30_150M_UR50D, esm2_t33_650M_UR50D (largest)
  esm2_model: "esm2_t33_650M_UR50D"  # Using the largest model for highest accuracy
  esm2_pretrained: true
  use_esm_embeddings: true
  freeze_pretrained: false  # Fine-tune the ESM-2 model
  embedding_dim: 1280  # ESM-2 t33 hidden dimension
  hidden_dim: 512
  num_attention_heads: 20
  num_hidden_layers: 2
  dropout_rate: 0.1
  max_sequence_length: 512

# Training Configuration
training:
  learning_rate: 5.0e-5
  warmup_steps: 100
  weight_decay: 0.01
  batch_size: 8
  epochs: 20
  early_stopping_patience: 3
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  use_fp16: true  # Use mixed precision training
  seed: 42

# CDR Masking Configuration
cdr_masking:
  mask_prob: 0.8  # Probability of masking a CDR
  cdr_regions:
    - "CDRH1"
    - "CDRH2"
    - "CDRH3"
    - "CDRL1"
    - "CDRL2"
    - "CDRL3"
  cdr_weighting: true  # Give more weight to CDR regions during training
  cdr_weight_factor: 2.0
  framework_mask_prob: 0.15  # Lower probability for framework regions
  whole_cdr_masking: true  # Mask entire CDR regions vs. individual residues

# Antibody Generation Configuration
antibody_generation:
  num_beams: 5  # Beam search for generation
  top_k: 50
  top_p: 0.95
  temperature: 0.7
  repetition_penalty: 1.2
  no_repeat_ngram_size: 3
  max_generation_attempts: 10
  min_cdr_length: 3
  max_cdr_length: 20

# Binding Prediction Configuration
binding_prediction:
  use_cross_attention: true
  toxin_embedding_dim: 1280
  binding_threshold: 0.5
  epitope_attention: true
  use_binding_data: true

# Dataset Configuration
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation_factor: 2
  use_binding_pairs: true
  max_training_examples: 10000

# Checkpoint Configuration
checkpoint:
  save_dir: "checkpoints/esm2_cdr"
  save_steps: 1000
  save_total_limit: 5
  logging_steps: 100
  eval_steps: 500
  use_wandb: false

# Default device (auto will use GPU if available, otherwise CPU)
device: "auto"